version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --proxy-headers=xforwarded
      - --proxy=edge
      - --hostname-strict=false
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    environment:
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://postgres-host:postgres-port/pg-db-name'
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: dbadmin-username
      KC_DB_PASSWORD: dbadmin-password
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: keycloak-admin-username
      KEYCLOAK_ADMIN_PASSWORD: keycloak-admin-password
    ports:
      - "8080:8080"
    restart: always

networks:
  default:
    external:
      name: leadersnet

      