version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    restart: always



networks:
  default:
    external:
      name: leadersnet