version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "37017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb_username
      - MONGO_INITDB_ROOT_PASSWORD=mongodb_password
    volumes:
      - ./mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "9092:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongodb_username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongodb_password
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  default:
    external:
      name: leadersnet
